hidden_sizes: [5, 10, 30]
hidden_layers: [2]
learning_rates: [0.001]
prior_vars: [0.001, 0.01, 0.05, 0.1, 0.5, 1., 5., 10., 50.]
hyperprior: False

epochs: 30000
search_space: 'small'
batch_size: 6000