hs: [200, 400, 800]
hidden_layers: 2
epochs: 500
search_space: 'small'
learning_rates: [0.001]
prior_vars: [1.]
activations: ['relu', 'tanh', 'sigmoid']
batch_size: 900
skips: [[[0,2], [0,3], [1,3], [[0,2], [0,3],], [[0,2], [1,3]], [[0,3], [1,3]], [[0,2]], [[0,3]], [[0,2]], []]